//Tasks Types
export const GET_TASKS = "GET_TASKS"
export const STORE_DATEHASHMAP = 'STORE_DATEHASHMAP'
export const GET_TASKS_ON_SPECIFIC_DATE = 'GET_TASKS_ON_SPECIFIC_DATE'
export const DELETE_TASK = "DELETE_TASK"

//User Types