//Tasks Types
export const GET_TASKS = "GET_TASKS"
export const STORE_DATEHASHMAP = 'STORE_DATEHASHMAP'
export const GET_TASKS_ON_SPECIFIC_DATE = 'GET_TASKS_ON_SPECIFIC_DATE'
export const DELETE_TASK = "DELETE_TASK"
export const ADD_TASK = "ADD_TASK"
export const EDIT_TASK = "EDIT_TASK"

//User Types

//Tag-members
export const SET_ITEMS_TO_SELECTED = 'SET_ITEMS_TO_SELECTED'
export const REMOVE_ITEMS_FROM_SELECTED = 'REMOVE_ITEMS_FROM_SELECTED'